// <auto-generated />
using FAQs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQs.Migrations
{
    [DbContext(typeof(FAQsContext))]
    [Migration("20240220025001_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQs.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = "gen",
                            CategoryName = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            CategoryName = "History"
                        });
                });

            modelBuilder.Entity("FAQs.Models.FAQ", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaqId"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FaqId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FQs");

                    b.HasData(
                        new
                        {
                            FaqId = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            CategoryId = "gen",
                            Question = "What is Bootstrap?",
                            TopicId = "bst"
                        },
                        new
                        {
                            FaqId = 2,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            CategoryId = "gen",
                            Question = "When is C#?",
                            TopicId = "c#"
                        },
                        new
                        {
                            FaqId = 3,
                            Answer = "A general purposse scripting language that executes in a web browser.",
                            CategoryId = "gen",
                            Question = "What is JavaScript?",
                            TopicId = "js"
                        },
                        new
                        {
                            FaqId = 4,
                            Answer = "In 2011",
                            CategoryId = "hist",
                            Question = "When was Bootstrap first released?",
                            TopicId = "bst"
                        },
                        new
                        {
                            FaqId = 5,
                            Answer = "In 2002",
                            CategoryId = "hist",
                            Question = "When was C# first released?",
                            TopicId = "C#"
                        },
                        new
                        {
                            FaqId = 6,
                            Answer = "On December 4, 1995.",
                            CategoryId = "hist",
                            Question = "When was JavaScriptk released?",
                            TopicId = "js"
                        });
                });

            modelBuilder.Entity("FAQs.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            TopicId = "c#",
                            TopicName = "C#"
                        },
                        new
                        {
                            TopicId = "js",
                            TopicName = "JavaScript"
                        },
                        new
                        {
                            TopicId = "bst",
                            TopicName = "BootStrap"
                        });
                });

            modelBuilder.Entity("FAQs.Models.FAQ", b =>
                {
                    b.HasOne("FAQs.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FAQs.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
